---
- name: Replace secret lines
  hosts: localhost
  gather_facts: yes
  become: no
  tasks:
    - name: Gather base64 es password
      shell: kubectl -n elastic-system  get secret esoperator-es-elastic-user  -o=jsonpath='{.data.elastic}'; echo
      register: espass64
      no_log: true

    - name: Gather plane text es password
      shell: kubectl -n elastic-system  get secret esoperator-es-elastic-user  -o=jsonpath='{.data.elastic}' | base64 --decode; echo
      register: espass
      no_log: true

    - name: Add a line in secret.yaml
      lineinfile:
        dest: "{{ item.path }}"
        regexp: password
        line: "{{ item.line }}"
        state: present
      with_items: "{{ secrets }}"
      no_log: true
