apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 100
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mysql:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 800Mi
          requests:
            cpu: 120m
            memory: 100Mi
