apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - fluentbit.yaml
  - https://raw.githubusercontent.com/cloudimix/myfiles/main/fluent_operator/fluent-operator-deployment.yaml
  - https://raw.githubusercontent.com/cloudimix/myfiles/main/fluent_operator/fluent-operator-clusterRole.yaml
  - https://raw.githubusercontent.com/cloudimix/myfiles/main/fluent_operator/fluent-operator-clusterRoleBinding.yaml
  - https://raw.githubusercontent.com/cloudimix/myfiles/main/fluent_operator/fluent-operator-serviceAccount.yaml
